name: Acryl dbt Impact Analysis
description: Comments on PRs with the impact of dbt changes.
inputs:
  datahub_gms_host:
    description: "DataHub GMS host."
    required: true
  datahub_gms_token:
    description: "DataHub GMS token."
    required: false
  datahub_frontend_url:
    description: "DataHub frontend URL."
    required: true

  dbt_profile_name:
    description: "dbt profile name from dbt_project.yml."
    required: true
  dbt_project_folder:
    description: "dbt project folder. Defaults to ."
    default: '.'

runs:
  using: "composite"
  steps:
    # - uses: actions/checkout@v3
    #   with:
    #     # We need git history for the git merge-base.
    #     fetch-depth: 0
    # TODO: For large repos, use this instead:
    # - uses: rmacklin/fetch-through-merge-base@v0

    # TODO: ensure that this is running on a PR
    
    - name: Run impact analysis
      id: impact-analysis
      shell: bash
      run: ${{ github.action_path }}/impact_analysis.sh
      env:
        DBT_PROFILE_NAME: ${{ inputs.dbt_profile_name }}}
        DBT_PROJECT_FOLDER: ${{ inputs.dbt_project_folder }}
        DATAHUB_GMS_HOST: ${{ inputs.datahub_gms_host }}
        DATAHUB_GMS_TOKEN: ${{ inputs.datahub_gms_token }}
        DATAHUB_FRONTEND_URL: ${{ inputs.datahub_frontend_url }}
        GITHUB_ACTION_PATH: ${{ github.action_path }}
        GITHUB_BASE_REF: ${{ github.base_ref }}

    # Post a comment on the PR.
    - uses: marocchino/sticky-pull-request-comment@v2
      with:
        header: acryl-impact-analysis
        message: ${{ steps.impact-analysis.outputs.IMPACT_ANALYSIS_MD }}
