name: CI
on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - uses: extractions/setup-just@v2
    
    - name: Setup
      run: |
        uv venv venv --python 3.10
        source venv/bin/activate
        just setup
    - name: Test
      run: |
        source venv/bin/activate
        just lint test
