name: Publish Major Version

on:
  release:
    types: [released, edited]

jobs:
  actions-tagger:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: Actions-R-Us/actions-tagger@v2
        with:
          publish_latest_tag: false
